### ISSUE TITLE
Find a way to enable "Preview Tabs" by default

### ISSUE THREAD

**Issue by leo** [leo/material-ui#4]
Atom's default setup contains a core-package called "Tabs" and the same package contains an option called "Preview Tabs" which opens new files within the same tab if the content of the current one hasn't been modified. It's basically like the default configuration in Sublime Text (see #2).

Since it's one of those features which make development more convenient and remove clutter, I think we should enable it by default after the theme's installation.

I don't yet know how to do this, but one thing I know for sure is that we should only enable it **after activation**. That means if a user wants to disable it again after installing our theme, we won't prevent him from doing so.

**Comment by leo** [comment]
Not completely sure about this one. Is this really something that's enabled by default in ST, @equinusocio? Or did that come with your theme?

Also what do you think, is it a good idea?

**Comment by leo** [comment]
Nah! We should add this as a "suggested configuration".

**Comment by equinusocio** [comment]
Yes, ST have this behavior enabled by default. Personally i hate this because if you click accidentally a large minified file the editor (Atom)  stop to respond and you have to wait a lot. Some time i have to restart the app.
