### ISSUE TITLE
Create a syntax theme

### ISSUE THREAD

**Issue by leo** [leo/material-ui#5]
**Cursor:**
- Should look like the system's native one (not too big)
- Colored like the theme's main green color

**Syntax:**
- Stronger colors (not that dull, like it's currently the case)
- Instead of showing a dot for each line that's too long, simply show nothing between the line numbers (like it's the case in the ST theme)

**Comment by equinusocio** [comment]
There is an utility that convert the color scheme from textmate (ST) to atom:
https://atom.io/docs/latest/hacking-atom-converting-from-textmate

**Comment by leo** [comment]
@equinusocio That sounds great! But it looks like someone is already using the name we would be using: https://atom.io/themes/material-syntax

What do you think, is it awesome enough? If you ask me, the syntax looks beautiful (although the repo looks a bit chaotic). :stuck_out_tongue_winking_eye:

**Comment by equinusocio** [comment]
Yes i know it :) I think make a new one from the original ST it's better. Maybe with the name "material-ui-syntax"? Consider that i've updated the color scheme right yesterday with some color changes (like variables color)

If you want we can use this one but every changes to it will be reflected to the UI that use syntax color variables

**Comment by leo** [comment]
Let's try [this](https://github.com/DaanDD/material-syntax/issues/4) before using such a long name for the package. If you want, you can add a comment to the issue, too. Maybe we can get him to release the handle :blush:

**Comment by leo** [comment]
@equinusocio The guy who owns the repo didn't respond to the issue. Since the repo is inactive since over a half year, he probably never will. So I've decided to ask the guys over at GitHub for help. Let's hope they'll release it! :see_no_evil:

**Comment by equinusocio** [comment]
We can ask (or grab it) here maybe
https://github.com/silvestreh/atom-material-syntax

PS: we have to make UI use the syntax variables, so the ui color change his main color based on the syntax background. This is  helpful to make darker and lighter UI simple changing the syntax. Watch this porting for atom: https://github.com/silvestreh/atom-material-ui

**Comment by leo** [comment]
Closing this for now. I think in Atom it's better to leave the choice of the syntax theme to the user. Packages are already using each others Less variables to definite certain colours, so it's okay to not create a special one for this theme, if you ask me.
