### ISSUE TITLE
Find and Find In Project panels huge

### ISSUE THREAD

**Issue by conchan** [leo/material-ui#7]
The panel seems to take up way more vertical space than necessary, and there doesn't seem to be a way to resize it manually. 

![screen shot 2015-12-11 at 10 21 48 am](https://cloud.githubusercontent.com/assets/662225/11747388/04ef287a-9ff1-11e5-82e5-ce5c8029c73a.png)

![screen shot 2015-12-11 at 10 20 59 am](https://cloud.githubusercontent.com/assets/662225/11747402/120b6c80-9ff1-11e5-8df0-2a72c2ea3090.png)

**Comment by leo** [comment]
Thank you for reporting this! But the bug was already fixed in https://github.com/leo/material-ui/commit/0180396b6ac901fb2fa650be5228f3260db4480f and its fix will be released together with version `1.0.4` later today. :blush:

**Comment by conchan** [comment]
Ah, thank you! :100:
